included:
  - Sources/Down
  - Tests

disabled_rules:
  - large_tuple
  - force_try
  - cyclomatic_complexity
  - identifier_name
  - line_length
  - unused_closure_parameter
  - force_cast
  - legacy_constructor
  - type_name
  - orphaned_doc_comment
  - void_return
  - xctfail_message
  
