included:
  - Sources/Down
  - Tests

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  ignores_case_statements: true

disabled_rules:
  - force_try
  - line_length
  - force_cast
  - xctfail_message
  
